#!/usr/bin/env python3
"""Normalize a ``combined_<code>.txt`` file to single-line, ``\\n``-escaped entries.

Background
----------
The build parser (``scripts/apply_combined_fr.py``) reads a combined file line by
line: a line is an entry only when it matches ``0x<offset>: <text>``. Every other
non-blank, non-comment line is **silently dropped**. EN/FR/DE combined files keep
each entry on a single physical line and encode in-game line breaks with the
literal escape ``\\n`` (two characters), so nothing is dropped.

``combined_it.txt`` was generated by ``process_italian_translations.py`` from a
JSON dump whose ``translated`` values contained **real newline characters**. They
were written verbatim, so multi-line strings spilled over several physical lines.
The parser then dropped every continuation line, truncating each multi-line
string to its first line in the built ROM (the most visible symptom being the
incomplete game intro).

This utility rewrites such a file in place so that each entry occupies a single
physical line with literal ``\\n`` escapes — exactly the format EN/FR/DE already
use and the parser expects. It is a faithful inverse of the bad generation: a
real newline inside an entry becomes ``\\n`` and a blank line inside an entry
becomes ``\\n\\n``.

Usage
-----
    python3 scripts/normalize_combined_multiline.py languages/it/combined_it.txt
    python3 scripts/normalize_combined_multiline.py <file> --check   # report only
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import List, Tuple

# Same shape the build parser uses to recognise an entry line.
OFFSET_RE = re.compile(r"^\s*0x[0-9A-Fa-f]+\s*:")
COMMENT_RE = re.compile(r"^\s*#")


def normalize_lines(lines: List[str]) -> Tuple[List[str], int]:
    """Return (normalized_lines, joined_continuation_count).

    ``lines`` are raw physical lines without trailing newlines. The result is a
    list of output lines (header/comment lines preserved verbatim, each entry on
    a single line with literal ``\\n`` escapes).
    """
    out: List[str] = []
    pending: List[str] | None = None  # pieces of the current entry (1 per phys line)
    joined = 0

    def flush() -> None:
        nonlocal pending
        if pending is None:
            return
        # Drop trailing blank pieces (entries never end on an empty line in the
        # canonical format); interior blanks survive as ``\n\n``.
        while len(pending) > 1 and pending[-1] == "":
            pending.pop()
        out.append("\\n".join(pending))
        pending = None

    for line in lines:
        if OFFSET_RE.match(line):
            flush()
            pending = [line]
        elif COMMENT_RE.match(line) and pending is None:
            # Header / standalone comment outside any entry: keep verbatim.
            out.append(line)
        elif pending is not None:
            # Continuation of the current entry (blank lines included).
            pending.append(line)
            joined += 1
        else:
            # Stray line before any entry (e.g. leading blank): keep verbatim.
            out.append(line)

    flush()
    return out, joined


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("path", type=Path, help="combined_<code>.txt to normalize")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Report how many continuation lines would be joined, without writing.",
    )
    args = parser.parse_args()

    if not args.path.exists():
        print(f"File not found: {args.path}", file=sys.stderr)
        return 2

    raw = args.path.read_text(encoding="utf-8")
    lines = raw.split("\n")
    # split() on a trailing newline yields a final empty element; preserve the
    # single trailing newline on write instead of treating it as content.
    trailing_newline = raw.endswith("\n")
    if trailing_newline and lines and lines[-1] == "":
        lines.pop()

    normalized, joined = normalize_lines(lines)

    if joined == 0:
        print(f"✓ {args.path} already single-line ({len(normalized)} lines).")
        return 0

    if args.check:
        print(f"{args.path}: {joined} continuation lines would be folded into their entries.")
        return 0

    text = "\n".join(normalized)
    if trailing_newline:
        text += "\n"
    args.path.write_text(text, encoding="utf-8")
    print(f"✓ Normalized {args.path}: folded {joined} continuation lines into their entries.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
