#!/usr/bin/env python3
"""Verify in-emulator that the HP/PS labels render as « PV ».

Consumes the VRAM dumps produced by ``scripts/probe_hp_vram.mts`` (which boots
the FR ROM in mGBA, opens the party screen and the summary stats page, and
dumps BG/OBJ VRAM under ``output/proofs/hp-vram/``), then checks the live
tiles against the « PV » art generated by ``patch_hp_labels_fr``:

1. party screen  — BG tiles 132/133 (rows 5-7) + 146/147 (rows 0-2) must
   equal the patched party-sheet label rows (tiles 51/52/59/60);
2. summary page  — the green bar label sprite (OBJ VRAM) must contain the
   patched block-0xE9B4B8 tiles 9-10;
3. summary page  — the grey stat label (BG VRAM) must contain the patched
   block-0xE9A460 tiles 100/101/116/117.

Run::

    npx tsx scripts/probe_hp_vram.mts full
    python3 scripts/verify_hp_labels_fr.py
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT_DIR))

from scripts.patch_hp_labels_fr import (  # noqa: E402
    GREEN_OLD_VARIANTS,
    GREY_OLD_TILES,
    PARTY_OLD_TILES,
    PARTY_ROWS,
    TILE,
    _draw_green_label,
    _draw_grey_label,
    _draw_party_label,
    _expected_new,
)

DUMP_DIR = ROOT_DIR / "output" / "proofs" / "hp-vram"

# VRAM tile indices observed on each screen (static tilemaps, savestate-driven)
PARTY_VRAM_TILES = {51: 132, 52: 133, 59: 146, 60: 147}


def _tile(data: bytes, idx: int) -> bytes:
    return data[idx * TILE:(idx + 1) * TILE]


def _expected_tiles(old: dict[int, str], draw) -> dict[int, bytes]:
    return {t: bytes.fromhex(h) for t, h in _expected_new(old, draw).items()}


def check_party(failures: list[str]) -> None:
    dump = DUMP_DIR / "party-vram-bg.bin"
    if not dump.exists():
        failures.append(f"missing dump {dump} — run probe_hp_vram.mts first")
        return
    vram = dump.read_bytes()
    expected = _expected_tiles(PARTY_OLD_TILES, _draw_party_label)
    # Only the label rows are comparable: the party box is composited over a
    # window canvas whose other rows hold the box border, not the sheet bg.
    label_rows: dict[int, list[int]] = {}
    for tl, tr, row in PARTY_ROWS:
        for t in (tl, tr):
            label_rows.setdefault(t, []).append(row)
    for sheet_tile, vram_tile in PARTY_VRAM_TILES.items():
        live = _tile(vram, vram_tile)
        want = expected[sheet_tile]
        for row in label_rows[sheet_tile]:
            if live[row * 4:row * 4 + 4] != want[row * 4:row * 4 + 4]:
                failures.append(
                    f"party label: vram tile {vram_tile} row {row} != PV art"
                )


def check_summary_green(failures: list[str]) -> None:
    dump = DUMP_DIR / "summary-skills-vram-obj.bin"
    if not dump.exists():
        failures.append(f"missing dump {dump} — run probe_hp_vram.mts first")
        return
    vram = dump.read_bytes()
    expected = _expected_tiles(GREEN_OLD_VARIANTS["ES « PS »"], _draw_green_label)
    pair = expected[9] + expected[10]
    if pair not in vram:
        failures.append("summary green bar label: PV sprite tiles not in OBJ VRAM")


def check_summary_grey(failures: list[str]) -> None:
    dump = DUMP_DIR / "summary-skills-vram-bg.bin"
    if not dump.exists():
        failures.append(f"missing dump {dump} — run probe_hp_vram.mts first")
        return
    vram = dump.read_bytes()
    expected = _expected_tiles(GREY_OLD_TILES, _draw_grey_label)
    for t, want in expected.items():
        if want not in vram:
            failures.append(f"summary grey label: PV tile {t} not in BG VRAM")


def main() -> int:
    failures: list[str] = []
    check_party(failures)
    check_summary_green(failures)
    check_summary_grey(failures)
    if failures:
        for f in failures:
            print(f"FAIL: {f}", file=sys.stderr)
        return 1
    print("verify_hp_labels_fr: PASS — party, summary bar and grey labels all render « PV »")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
